### ISSUE TITLE
get_inverse(...) unreliable

### ISSUE THREAD

**Issue by t-github** [aothms/IfcOpenShell#20]
Hi,

The get_inverse method under the IfcParse namespace seems to be unreliable. For an example run the following command with a file of your choice which contains layer assignments:

```
ifc.open(filename).by_type('IfcPresentationLayerAssignment')[0].get_argument('AssignedItems')[0].get_inverse('LayerAssignments')
```

The inverse mapping 'LayerAssignments' on IfcRepresentation as defined [here](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcrepresentationresource/lexical/ifcrepresentation.htm) returns an empty array, rather than including the layer assigned to the representation.

**Comment by aothms** [comment]
Hi,

Cleaning up old tickets. This has been fixed a while ago in the sourceforge repository:
https://sourceforge.net/p/ifcopenshell/svn/282/

Please stick to that repository until a proper mirror to github is in place.

Kind regards,
Thomas
